---
# caddy.yml — Provision and configure Caddy reverse proxy LXC on PVE01
#
# Prerequisites:
#   - 1Password CLI (op) v2+ signed in on the controller
#   - community.general collection installed
#   - Unifi DHCP reservation for caddy on dProxy (VLAN 50)
#
# Usage:
#   ansible-playbook caddy.yml
#   ansible-playbook caddy.yml --tags template     # Only ensure LXC template
#   ansible-playbook caddy.yml --tags provision     # Only create the LXC
#   ansible-playbook caddy.yml --tags configure     # Only configure Caddy

# ── Phase 0: Ensure Trixie LXC template exists ─────────────────
- name: Ensure Debian 13 LXC template is available
  hosts: pve01
  become: true
  gather_facts: false
  tags: [template, provision]

  vars:
    template_cache_dir: "/var/lib/vz/template/cache"
    dab_work_dir: "/root/dab/{{ pve_lxc_template_distro }}"
    dab_git_base: "https://git.proxmox.com/?p=dab-pve-appliances.git;a=blob_plain;hb=HEAD;f=debian-13-trixie-std-64"

  tasks:
    - name: Check if a Trixie template already exists in cache
      ansible.builtin.find:
        paths: "{{ template_cache_dir }}"
        patterns: "{{ pve_lxc_template_distro }}_*.tar.*"
      register: cached_templates

    - name: Try to download template via pveam
      when: cached_templates.matched == 0
      block:
        - name: Update pveam template index
          ansible.builtin.command: pveam update
          changed_when: true

        - name: Find latest available template
          ansible.builtin.shell: >
            pveam available --section system
            | grep '{{ pve_lxc_template_distro }}'
            | tail -1
            | awk '{print $2}'
          register: pveam_template
          changed_when: false

        - name: Download template via pveam
          ansible.builtin.command: >
            pveam download local {{ pveam_template.stdout }}
          when: pveam_template.stdout | length > 0
          register: pveam_download
          changed_when: pveam_download.rc == 0

    - name: Fall back to building template with dab
      when:
        - cached_templates.matched == 0
        - pveam_download is not defined or pveam_download is skipped or pveam_download is failed
      block:
        - name: Install dab
          ansible.builtin.apt:
            name: dab
            state: present
            update_cache: true

        - name: Create dab working directory
          ansible.builtin.file:
            path: "{{ dab_work_dir }}"
            state: directory
            mode: "0755"

        - name: Download dab.conf
          ansible.builtin.get_url:
            url: "{{ dab_git_base }}/dab.conf"
            dest: "{{ dab_work_dir }}/dab.conf"
            mode: "0644"

        - name: Download Makefile
          ansible.builtin.get_url:
            url: "{{ dab_git_base }}/Makefile"
            dest: "{{ dab_work_dir }}/Makefile"
            mode: "0644"

        - name: Build template (takes a few minutes)
          ansible.builtin.command:
            cmd: make
            chdir: "{{ dab_work_dir }}"
          register: dab_build
          changed_when: dab_build.rc == 0

        - name: Copy built template to cache
          ansible.builtin.shell: >
            cp {{ dab_work_dir }}/{{ pve_lxc_template_distro }}_*.tar.*
            {{ template_cache_dir }}/
          changed_when: true

    - name: Detect template filename in cache
      ansible.builtin.find:
        paths: "{{ template_cache_dir }}"
        patterns: "{{ pve_lxc_template_distro }}_*.tar.*"
      register: final_template

    - name: Set template fact for provisioning
      ansible.builtin.set_fact:
        pve_lxc_template_resolved: "local:vztmpl/{{ final_template.files[0].path | basename }}"
      when: final_template.matched > 0

# ── Phase 1: Provision LXC container ───────────────────────────
- name: Provision Caddy LXC container on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  tags: [provision]

  vars:
    proxmox_host: "pve01"
    proxmox_api_host: "{{ hostvars['pve01']['ansible_host'] }}"
    proxmox_api_user: "root@pam"
    lxc_template: >-
      {{ hostvars['pve01']['pve_lxc_template_resolved']
         | default('local:vztmpl/' + pve_lxc_template_distro + '_latest.tar.zst') }}

  tasks:
    - name: Create Caddy LXC container
      community.general.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ pve_01_api_token_id }}"
        api_token_secret: "{{ pve_01_api_token_secret }}"
        node: "{{ proxmox_host }}"
        hostname: "caddy"
        vmid: 150
        ostemplate: "{{ lxc_template }}"
        storage: "local-lvm"
        disk: "4"
        cores: 1
        memory: 256
        swap: 256
        nameserver: "{{ caddy_nameserver }}"
        searchdomain: "{{ caddy_search_domain }}"
        net:
          net0: "name=eth0,bridge=vmbr0,tag=50,ip=dhcp,firewall=1"
        pubkey: "{{ ops_ssh_public_key }}"
        onboot: true
        unprivileged: true
        features:
          - nesting=1
        state: present

    - name: Start Caddy LXC container
      community.general.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ pve_01_api_token_id }}"
        api_token_secret: "{{ pve_01_api_token_secret }}"
        node: "{{ proxmox_host }}"
        vmid: 150
        state: started

    - name: Wait for container to get DHCP lease and become reachable
      ansible.builtin.wait_for:
        host: "{{ hostvars['caddy']['ansible_host'] }}"
        port: 22
        delay: 10
        timeout: 90

# ── Phase 2: Configure Caddy ───────────────────────────────────
- name: Configure Caddy reverse proxy
  hosts: caddy
  become: true
  gather_facts: true
  tags: [configure]

  roles:
    - role: common
    - role: caddy