---
# caddy.yml — Provision and configure Caddy reverse proxy LXC on PVE-01
#
# Prerequisites:
#   - 1Password CLI (op) v2+ signed in on the controller
#   - community.general collection installed
#   - Unifi DHCP reservation for caddy on dProxy (VLAN 50)
#
# Usage:
#   ansible-playbook caddy.yml
#   ansible-playbook caddy.yml --tags template     # Only ensure LXC template
#   ansible-playbook caddy.yml --tags provision     # Only create the LXC
#   ansible-playbook caddy.yml --tags configure     # Only configure Caddy

# ── Phase 0: Ensure Trixie LXC template exists ─────────────────
- import_playbook: roles/common/tasks/ensureTemplate.yml

# ── Phase 1: Provision LXC container ───────────────────────────
- name: Provision Caddy LXC container on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  become: false 
  tags: [provision] 

  vars:
    proxmox_host: "pve-01"
    proxmox_api_host: "{{ hostvars['pve-01']['ansible_host'] }}"
    lxc_template: >-
      {{ hostvars['pve-01']['pve_lxc_template_resolved']
         | default('local:vztmpl/' + pve_lxc_template_distro + '_latest.tar.zst') }}

  tasks:
    - name: Create Caddy LXC container
      community.proxmox.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ pve_01_api_user }}"
        api_token_id: "{{ pve_01_api_token_id }}"
        api_token_secret: "{{ pve_01_api_token_secret }}"
        validate_certs: false
        node: "{{ proxmox_host }}"
        hostname: "caddy"
        vmid: 150
        ostemplate: "{{ lxc_template }}"
        storage: "local-lvm"
        disk: "4"
        cores: 1
        memory: 512
        swap: 0
        nameserver: "{{ hostvars['caddy']['caddy_nameserver'] }}"
        searchdomain: "{{ hostvars['caddy']['caddy_search_domain'] }}"
        netif: '{"net0":"name=eth0,bridge=vmbr0,tag=50,ip=dhcp,firewall=1"}'
        pubkey: "{{ ops_ssh_public_key }}"
        onboot: true
        unprivileged: true
        features:
          - nesting=1
        state: present

    - name: Start Caddy LXC container
      community.proxmox.proxmox:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ pve_01_api_user }}"
        api_token_id: "{{ pve_01_api_token_id }}"
        api_token_secret: "{{ pve_01_api_token_secret }}"
        validate_certs: false
        node: "{{ proxmox_host }}"
        vmid: 150
        state: started

    - name: Wait for container to get DHCP lease and become reachable
      ansible.builtin.wait_for:
        host: "{{ hostvars['caddy']['ansible_host'] }}"
        port: 22
        delay: 10
        timeout: 90

# ── Phase 2: Configure Caddy ───────────────────────────────────
- name: Configure Caddy reverse proxy
  hosts: caddy
  become: true
  gather_facts: true
  tags: [configure]

  roles:
    - role: common
    - role: caddy